# Project Chimera - Mechanical Reference Document (Lite) v2.1
**Focus:** Core Gameplay Loop & Combat Mechanics
**Engine:** Godot 4.x (Compatibility Renderer)
**Perspective:** First-Person (FMV/Video-Based)

---

## 1. The Core Loop (Roguelite Structure)

1.  **The Hub:** Player spends meta-currency (`Refined Data` / `Sentience Points`) on Skill Trees to unlock cards, Implants, and Outfits. Selects Loadout ("Chassis") and Difficulty ("Act").
2.  **The Run (Gauntlet):** Procedurally generated node map (~15-18 nodes).
    * **Encounters:** Turn-based Sex Combat vs. NPCs.
    * **Mid-Boss:** Guaranteed "Rival Encounter" (unlocks `Position:` cards).
    * **Final Boss:** Act Boss.
3.  **The Reward:**
    * **Victory:** Gain `Raw Essence` (Shop currency).
    * **Loss:** Run ends.
4.  **Conversion:** Post-run, `Raw Essence` is converted to persistent Meta-Currency based on player choice (Corporate vs. Rebel).

---

## 2. Combat Mechanics (The Sex Battle)

### 2.1 Victory & Defeat Conditions
* **Victory:** Deplete NPC **Composure** to 0 (Character Climaxes).
* **Defeat:** Player **Arousal** reaches 100 (System Overload/Climax).

### 2.2 The Defensive Hierarchy (Damage Logic)
Damage is applied sequentially through three layers.
1.  **Layer 1: Focus (Shield)**
    * **Source:** Generated by `Defensive` cards. Absorbs all incoming damage.
    * **Decay:** Halved (rounded down) at end of owner's turn.
2.  **Layer 2: Inhibition (Armor)**
    * **Source:** Persistent stat determined by **Outfit**. Absorbs damage once Focus is depleted.
    * **State Change:** Reaching 0 triggers **`Exposed`** state.
3.  **Layer 3: Composure (Health)**
    * **Source:** Core health pool. Only takes damage if Focus and Inhibition are 0 (or attack has `Piercing`).

### 2.3 The Arousal Meter (The Heat System)
**Core Concept:** A "One-Way Ratchet." Arousal (0-100) represents the player's physiological state. It is easy to raise (high momentum) but difficult/expensive to lower.

#### Mechanical Pillar 1: Sensitivity (The Risk)
As Arousal increases, the player becomes hypersensitive, taking increased damage from all sources.

| Tier | State Name | Range | Incoming Dmg Multiplier | Visual/Audio Cue |
| :--- | :--- | :--- | :--- | :--- |
| **I** | **Stable** | 0 - 29 | **1.0x** (Normal) | HUD is clean. Breathing is steady. |
| **II** | **Flushed** | 30 - 59 | **1.2x** (+20% Dmg) | Mild screen vignetting (pink). Soft heartbeat audio. |
| **III** | **High** | 60 - 89 | **1.5x** (+50% Dmg) | Strong vignetting. Audible heavy breathing. HUD jitters. |
| **IV** | **Critical** | 90 - 99 | **2.0x** (+100% Dmg) | Screen edges pulse. Heartbeat loud. "CRITICAL" flash. |

#### Mechanical Pillar 2: Threshold Gating (The Reward)
Higher Arousal tiers unlock the true potential of the deck.
* **Card Evolution:** "Morph Cards" automatically upgrade their effects when entering a higher tier.
* **Gated Access:** Powerful `Intimate` cards may require Tier III (High) to be playable.

#### Mechanical Pillar 3: Release (The Management)
To manage risk, players use **Release** cards (formerly "Spenders").
* **Loop:** Build Arousal to unlock power -> Play "Release" card to dump Arousal into damage -> Return to Safety (Tier I/II).

### 2.4 Entity States
* **Guarded:** Active while **Inhibition > 0**.
    * Provides damage reduction vs. Physical attacks (`Guarded [Upper]` / `Guarded [Lower]`).
    * `Verbal` attacks bypass Guarded.
* **Exposed:** Active when **Inhibition == 0**.
    * Removes all Guarded damage reduction.
    * **Unlocks:** Allows usage of high-power `Intimate` cards.

### 2.5 NPC Mechanics: Reactive Escalation
NPC behavior is deterministic and reactive. Their action selection is primarily driven by the **Player's Current Arousal Tier**.

* **Tier I (Stable) - The Approach:**
    * *Logic:* Verbal teases, light touches, Observe actions.
    * *Visuals:* Admiring glances, compliments, hand on shoulder.
    * *Goal:* Build Tension, test Focus.
* **Tier II (Flushed) - The Escalation:**
    * *Logic:* Physical [Upper Body] actions, moderate Verbal pressure.
    * *Visuals:* Breaking personal space, kissing, groping.
    * *Goal:* Break Inhibition (Armor).
* **Tier III (High) - The Intimacy:**
    * *Logic:* Heavy Physical [Lower Body] actions, Intimate openers.
    * *Visuals:* Explicit sexual contact, oral stimulation, grinding.
    * *Goal:* Rapidly spike Player Arousal to critical.
* **Tier IV (Critical) - The Finishers:**
    * *Logic:* "Ultimate" moves, Ride/Throatf**k variants.
    * *Visuals:* High-intensity climactic acts.
    * *Goal:* Force immediate Game Over (Climax).

---

## 3. The Card System

### 3.1 Hand & Deck Logic
* **Draw Rule:** Turn 1: Draw 5. Turn 2+: Draw to 5. If holding 5+, draw 1.
* **Discard Rule:** Full discard at end of turn (unless `Retain`).
* **Max Hand:** 10 Cards.

### 3.2 Revised Keywords & Mechanics
* **`Morph: [Tier]`**: If player is at [Tier] or higher, this card transforms into a stronger version.
* **`Threshold: X`**: Card can only be played if current Arousal is X or higher.
* **`Suppress`**: Prevents Arousal Gain from enemy attacks for 1 turn. (Pauses momentum).
* **`Cool Down: X`**: Reduces current Arousal by X. (Reverses momentum - Rare/Expensive).
* **`Release: X`**: Additional Cost: Spend (reduce) Arousal by X to play this card. (Dumps heat).
* **`Vent`**: Reduce Arousal by X, but deal X damage to Player Focus/Energy. (Emergency dump).

### 3.3 Starting Deck (Standard Issue Chassis)
*Total Size: 10 Cards. Balanced for Heat Management.*

**Generators (Build Heat)**
1.  **Tease (x2):** `Verbal`. Deal 4 Composure. Apply +5 Player Arousal.
2.  **Grind (x2):** `Physical`. Deal 6 Composure. Apply +8 Player Arousal.

**Thresholds / Morphs (The Payoff)**
3.  **Heavy Petting (x2):** `Physical`. `Threshold: 30`. Deal 12 Composure. (Efficient damage, requires Flushed state).
4.  **Dirty Talk (x1):** `Verbal`. `Threshold: 50`. Deal 15 Composure. Ignores Armor (Inhibition).

**Releases (The Safety Valve)**
5.  **Cold Shower (x1):** `Mental`. `Cool Down: 20`. Gain 5 Focus. (Pure defense/reset).
6.  **Climactic Thrust (x1):** `Intimate`. `Release: 40`. Deal 30 Composure. (Finisher. Dumps heat for massive damage).

**Utility**
7.  **Steady Breath (x1):** `Mental`. Gain 8 Focus. Draw 1 card.

---

## 4. Technical Implementation (Godot)

### 4.1 Rendering & Assets
* **Renderer:** Godot Compatibility (OpenGL 3.3).
* **Visual Style:** "Cinematic Turn" using Pre-rendered Video (`.webm`).
    * `Neutral_Loop.webm`: Idle state.
    * `Action_Clips.webm`: Triggered by card plays.
* **GenAI Pipeline:** 1. Base Image (LoRA) -> 2. Image-to-Video -> 3. Post-Process -> 4. Godot `VideoStreamPlayer`.

### 4.2 UI Layout (HUD)
* **Center:** NPC Video Feed + NPC Status Bars.
* **Visual Cues:**
    * *Tier II:* Pink Vignette.
    * *Tier III:* Heavy Vignette + Jitter.
    * *Tier IV:* Pulsing Edges + "CRITICAL" text.
* **Bottom:** Card Hand (Fan) + AP Pips.
* **Periphery:** Player Vitals (Left) + Arousal Meter (Right).

---

## 5. Balancing Targets

* **Average Encounter:** ~5 Minutes.
* **Sensitivity Curve:** Player should feel safe in Tier I, powerful but threatened in Tier II/III, and in immediate danger in Tier IV.
* **NPC Pacing:** NPCs must strictly adhere to the Tier Logic to ensure the fight feels like a natural seduction curve rather than random violence.
